export class Statistique {
  id: number = 0;
  niveau: number = 0;
  vie: number = 0;
  terre: number = 0;
  feu: number = 0;
  air: number = 0;
  eau: number = 0;
  sagesse: number = 0;
  hate: number = 0;
  puissance: number = 0;
  precision: number = 0;
  dexterite: number = 0;
  energie: number = 0;
  critiqueChance: number = 0;
  critiqueDommage: number = 0;
  resistanceTerre: number = 0;
  resistanceFeu: number = 0;
  resistanceAir: number = 0;
  resistanceEau: number = 0;
}
